# Site settings
title: Great New Blog Title
author:
  name: Alberto Ferrari
  email: alberto-ferrari@outlook.it
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll-theme-minimal
